# Generated by Django 3.2.1 on 2022-01-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_assessment',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
